apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: identity-service
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001