apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: identity-service:latest
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:
            name: microservices-env
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

