apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: media-service
  ports:
  - port: 3002
    targetPort: 3002
    nodePort: 30002