apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: post-service
  ports:
  - port: 3003
    targetPort: 3003
    nodePort: 30003