apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: amqp             # <— name required for port 5672
      port: 5672
      targetPort: 5672
    - name: management       # <— name required for port 15672
      port: 15672
      targetPort: 15672
