apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: microservices
spec:
  type: NodePort
  selector:
    app: search-service
  ports:
  - port: 3004
    targetPort: 3004
    nodePort: 30004