apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: search-service:latest
        ports:
        - containerPort: 3004
        envFrom:
        - secretRef:
            name: microservices-env
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

